version: "3.0"

services:
  node:
    build: .
    container_name: Server
    depends_on:
      - mongo
    ports:
      - 7060:1111
    environment:
      - APP_NAME=WebServ1Projekt
      - SERVER_ROOT=.
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: node server.js
  mongo:
    image: clutteredcode/mongo-alpine
    environment:
      - MONGO_USERNAME=jamal
      - MONGO_PASSWORD=jamal
    container_name: Database
    expose:
      - "27017"
    ports:
     - 27017:27017
    volumes:
      - db:/data/db
  mongodata:
    image: tianon/true
    container_name: Database-data
    volumes:
      - db:/data/db

volumes:
  db: